# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Consul
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Site translations
homepage:
  welcome:
    es: "Bienvenido a CONSUL"
    en: "Welcome to CONSUL"
  tagline:
    es: "Aplicaci贸n de Gobierno abierto y Participaci贸n ciudadana"
    en: "Citizen Participation and Open Government Application"
  button_github:
    es: "Ver c贸digo en github"
    en: "See code on github"
  repositories_list:
    es: "Lista completa de repositorios"
    en: "Complete list of repositories"
license:
  button_github:
    es: "Ver c贸digo en github"
    en: "See code on github"
