# Site settings
email: extension.institucional@madrid.es
description: >
  Software libre para participaci√≥n ciudadana. Inteligencia colectiva y democracia directa digital para ciudades inteligentes. Abriendo gobiernos.
baseurl: ""
url: "http://www.consulproject.org/"
twitter_username: abriendomadrid
github_username: consul

# Build settings
markdown: kramdown
